using AgileDotNetHtml.Interfaces;
using System;
using System.Collections.Generic;

namespace AgileDotNetHtml
{
    public class Html5Standarts : IHtmlStandarts
    {
        private string[] _standartHtmlTags => new string[] {
            "<!---->",
            "<!DOCTYPE>",
            "<a>",
            "<abbr>",
            "<acronym>",
            "<address>",
            "<applet>",
            "<area>",
            "<article>",
            "<aside>",
            "<audio>",
            "<b>",
            "<base>",
            "<basefont>",
            "<bdi>",
            "<bdo>",
            "<big>",
            "<blockquote>",
            "<body>",
            "<br>",
            "<button>",
            "<canvas>",
            "<caption>",
            "<center>",
            "<cite>",
            "<code>",
            "<col>",
            "<colgroup>",
            "<data>",
            "<datalist>",
            "<dd>",
            "<del>",
            "<details>",
            "<dfn>",
            "<dialog>",
            "<dir>",
            "<div>",
            "<dl>",
            "<dt>",
            "<em>",
            "<embed>",
            "<fieldset>",
            "<figcaption>",
            "<figure>",
            "<font>",
            "<footer>",
            "<form>",
            "<frame>",
            "<frameset>",
            "<h1>",
            "<h2>",
            "<h3>",
            "<h4>",
            "<h5>",
            "<h6>",
            "<head>",
            "<header>",
            "<hr>",
            "<html>",
            "<i>",
            "<iframe>",
            "<img>",
            "<input>",
            "<ins>",
            "<kbd>",
            "<label>",
            "<legend>",
            "<li>",
            "<link>",
            "<main>",
            "<map>",
            "<mark>",
            "<meta>",
            "<meter>",
            "<nav>",
            "<noframes>",
            "<noscript>",
            "<object>",
            "<ol>",
            "<optgroup>",
            "<option>",
            "<output>",
            "<p>",
            "<param>",
            "<picture>",
            "<pre>",
            "<progress>",
            "<q>",
            "<rp>",
            "<rt>",
            "<ruby>",
            "<s>",
            "<samp>",
            "<script>",
            "<section>",
            "<select>",
            "<small>",
            "<source>",
            "<span>",
            "<strike>",
            "<strong>",
            "<style>",
            "<sub>",
            "<summary>",
            "<sup>",
            "<svg>",
            "<table>",
            "<tbody>",
            "<td>",
            "<template>",
            "<textarea>",
            "<tfoot>",
            "<th>",
            "<thead>",
            "<time>",
            "<title>",
            "<tr>",
            "<track>",
            "<tt>",
            "<u>",
            "<ul>",
            "<var>",
            "<video>",
            "<wbr>"
                };
        private Dictionary<string, string[]> _standartHtmlAttrubuteTagsDict => new Dictionary<string, string[]>()
        {
             {"accept", new string[] { "<input>" }} ,
             {"accept-charset", new string[] { "<form>"}} ,
             {"accesskey", null} ,
             {"action", new string[] { "<form>"}} ,
             {"alt", new string[] { "<area>","<img>","<input>"}} ,
             {"async", new string[] { "<script>"}} ,
             {"autocomplete", new string[] { "<form>","<input>"}} ,
             {"autofocus", new string[] { "<button>","<input>","<select>","<textarea>"}} ,
             {"autoplay", new string[] { "<audio>","<video>"}} ,
             {"charset", new string[] { "<meta>","<script>"}} ,
             {"checked", new string[] { "<input>"}} ,
             {"cite", new string[] { "<del>","<ins>"}} ,
             {"class", null} ,
             {"cols", new string[] { "<textarea>"}} ,
             {"colspan", new string[] { "<td>","<th>"}} ,
             {"content", new string[] { "<meta>"}} ,
             {"contenteditable", null} ,
             {"controls", new string[] { "<audio>","<video>"}} ,
             {"coords", new string[] { "<area>"}} ,
             {"data", new string[] { "<object>"}} ,
             {"data-*", null} ,
             {"datetime", new string[] { "<del>","<ins>","<time>"}} ,
             {"default", new string[] { "<track>"}} ,
             {"defer", new string[] { "<script>"}} ,
             {"dir", null} ,
             {"dirname", new string[] { "<input>","<textarea>"}} ,
             {"disabled", new string[] { "<button>","<fieldset>","<input>","<option>","<select>","<textarea>"}} ,
             {"download", new string[] { "<a>","<area>"}} ,
             {"draggable", null} ,
             {"enctype", new string[] { "<form>"}} ,
             {"for", new string[] { "<output>", "<label>"}} ,
             {"form", new string[] { "<button>","<fieldset>","<input>","<meter>","<object>","<output>","<select>","<textarea>"}} ,
             {"formaction", new string[] { "<button>","<input>"}} ,
             {"headers", new string[] { "<td>","<th>"}} ,
             {"height", new string[] { "<embed>","<iframe>","<img>","<input>","<object>","<video>"}} ,
             {"hidden", null} ,
             {"high", new string[] { "<meter>"}} ,
             {"href", new string[] { "<a>","<area>","<base>","<link>"}} ,
             {"hreflang", new string[] { "<a>","<area>","<link>"}} ,
             {"http-equiv", new string[] { "<meta>"}} ,
             {"id", null} ,
             {"ismap", new string[] { "<img>"}} ,
             {"kind", new string[] { "<track>"}} ,
             {"label", new string[] { "<track>","<option>","<optgroup>"}} ,
             {"lang", null} ,
             {"list", new string[] { "<input>"}} ,
             {"loop", new string[] { "<audio>","<video>"}} ,
             {"low", new string[] { "<meter>"}} ,
             {"max", new string[] { "<input>","<meter>","<progress>"}} ,
             {"maxlength", new string[] { "<input>","<textarea>"}} ,
             {"media", new string[] { "<a>","<area>","<link>","<source>","<style>"}} ,
             {"method", new string[] { "<form>"}} ,
             {"min", new string[] { "<input>","<meter>"}} ,
             {"multiple", new string[] { "<input>","<select>"}} ,
             {"muted", new string[] { "<video>","<audio>"}} ,
             {"name", new string[] { "<button>","<fieldset>","<form>","<iframe>","<input>","<map>","<meta>","<object>","<output>","<param>","<select>","<textarea>"}} ,
             {"novalidate", new string[] { "<form>"}} ,
             {"onabort", new string[] { "<audio>","<embed>","<img>","<object>","<video>"}} ,
             {"onafterprint", new string[] { "<body>"}} ,
             {"onbeforeprint", new string[] { "<body>"}} ,
             {"onbeforeunload", new string[] { "<body>"}} ,
             {"onblur", new string[] { }} ,
             {"oncanplay", new string[] { "<audio>","<embed>","<object>","<video>"}} ,
             {"oncanplaythrough", new string[] { "<audio>","<video>"}} ,
             {"onchange", new string[] { }} ,
             {"onclick", new string[] { }} ,
             {"oncontextmenu", new string[] { }} ,
             {"oncopy", new string[] { }} ,
             {"oncuechange", new string[] { "<track>"}} ,
             {"oncut", new string[] { }} ,
             {"ondblclick", new string[] { }} ,
             {"ondrag", new string[] { }} ,
             {"ondragend", new string[] { }} ,
             {"ondragenter", new string[] { }} ,
             {"ondragleave", new string[] { }} ,
             {"ondragover", new string[] { }} ,
             {"ondragstart", new string[] { }} ,
             {"ondrop", new string[] { }} ,
             {"ondurationchange", new string[] { "<audio>","<video>"}} ,
             {"onemptied", new string[] { "<audio>","<video>"}} ,
             {"onended", new string[] { "<audio>","<video>"}} ,
             {"onerror", new string[] { "<audio>","<body>","<embed>","<img>","<object>","<script>","<style>","<video>"}} ,
             {"onfocus", new string[] { }} ,
             {"onhashchange", new string[] { "<body>"}} ,
             {"oninput", new string[] { }} ,
             {"oninvalid", new string[] { }} ,
             {"onkeydown", new string[] { }} ,
             {"onkeypress", new string[] { }} ,
             {"onkeyup", new string[] { }} ,
             {"onload", new string[] { "<body>","<iframe>","<img>","<input>","<link>","<script>","<style>"}} ,
             {"onloadeddata", new string[] { "<audio>","<video>"}} ,
             {"onloadedmetadata", new string[] { "<audio>","<video>"}} ,
             {"onloadstart", new string[] { "<audio>","<video>"}} ,
             {"onmousedown", new string[] { }} ,
             {"onmousemove", new string[] { }} ,
             {"onmouseout", new string[] { }} ,
             {"onmouseover", new string[] { }} ,
             {"onmouseup", new string[] { }} ,
             {"onmousewheel", new string[] { }} ,
             {"onoffline", new string[] { "<body>"}} ,
             {"ononline", new string[] { "<body>"}} ,
             {"onpagehide", new string[] { "<body>"}} ,
             {"onpageshow", new string[] { "<body>"}} ,
             {"onpaste", new string[] { }} ,
             {"onpause", new string[] { "<audio>","<video>"}} ,
             {"onplay", new string[] { "<audio>","<video>"}} ,
             {"onplaying", new string[] { "<audio>","<video>"}} ,
             {"onpopstate", new string[] { "<body>"}} ,
             {"onprogress", new string[] { "<audio>","<video>"}} ,
             {"onratechange", new string[] { "<audio>","<video>"}} ,
             {"onreset", new string[] { "<form>"}} ,
             {"onresize", new string[] { "<body>"}} ,
             {"onscroll", new string[] { }} ,
             {"onsearch", new string[] { "<input>"}} ,
             {"onseeked", new string[] { "<audio>","<video>"}} ,
             {"onseeking", new string[] { "<audio>","<video>"}} ,
             {"onselect", new string[] { }} ,
             {"onstalled", new string[] { "<audio>","<video>"}} ,
             {"onstorage", new string[] { "<body>"}} ,
             {"onsubmit", new string[] { "<form>"}} ,
             {"onsuspend", new string[] { "<audio>","<video>"}} ,
             {"ontimeupdate", new string[] { "<audio>","<video>"}} ,
             {"ontoggle", new string[] { "<details>"}} ,
             {"onunload", new string[] { "<body>"}} ,
             {"onvolumechange", new string[] { "<audio>","<video>"}} ,
             {"onwaiting", new string[] { "<audio>","<video>"}} ,
             {"onwheel", new string[] { }} ,
             {"open", new string[] { "<details>"}} ,
             {"optimum", new string[] { "<meter>"}} ,
             {"pattern", new string[] { "<input>"}} ,
             {"placeholder", new string[] { "<input>","<textarea>"}} ,
             {"poster", new string[] { "<video>"}} ,
             {"preload", new string[] { "<audio>","<video>"}} ,
             {"readonly", new string[] { "<input>","<textarea>"}} ,
             {"rel", new string[] { "<a>","<area>","<form>","<link>"}} ,
             {"required", new string[] { "<input>","<select>","<textarea>"}} ,
             {"reversed", new string[] { "<ol>"}} ,
             {"rows", new string[] { "<textarea>"}} ,
             {"rowspan", new string[] { "<td>","<th>"}} ,
             {"sandbox", new string[] { "<iframe>"}} ,
             {"scope", new string[] { "<th>"}} ,
             {"selected", new string[] { "<option>"}} ,
             {"shape", new string[] { "<area>"}} ,
             {"size", new string[] { "<input>","<select>"}} ,
             {"sizes", new string[] { "<img>","<link>","<source>"}} ,
             {"span", new string[] { "<col>","<colgroup>"}} ,
             {"spellcheck", null} ,
             {"src", new string[] { "<audio>","<embed>","<iframe>","<img>","<input>","<script>","<source>","<track>","<video>"}} ,
             {"srcdoc", new string[] { "<iframe>"}} ,
             {"srclang", new string[] { "<track>"}} ,
             {"srcset", new string[] { "<img>","<source>"}} ,
             {"start", new string[] { "<ol>"}} ,
             {"step", new string[] { "<input>"}} ,
             {"style", null} ,
             {"tabindex", null} ,
             {"target", new string[] { "<a>","<area>","<base>","<form>"}} ,
             {"title", null} ,
             {"translate", null} ,
             {"type", new string[] { "<a>","<button>","<embed>","<input>","<link>","<menu>","<object>","<script>","<source>","<style>"}} ,
             {"usemap", new string[] { "<img>","<object>"}} ,
             {"value", new string[] { "<button>","<input>","<li>","<option>","<meter>","<progress>","<param>"}} ,
             {"width", new string[] { "<embed>","<iframe>","<img>","<input>","<object>","<video>"}} ,
             {"wrap", new string[] { "<textarea>"}}

        };
        private string[] _selfClosingTags => new string[] {
            "<area />",
            "<base />",
            "<br />",
            "<embed />",
            "<hr /> ",
            "<iframe /> ",
            "<img />",
            "<input />",
            "<link />",
            "<meta />",
            "<param />",
            "<source />",
            "<track /> "
        };
        private string[] _inputTypes => new string[]
        {
             "button",
             "checkbox",
             "color",
             "date",
             "datetime-local",
             "email",
             "file",
             "hidden",
             "image",
             "month",
             "number",
             "password",
             "radio",
             "range",
             "reset",
             "search",
             "submit",
             "tel",
             "text",
             "time",
             "url",
             "week",
        };
        public string HtmlVersion => "5";
        public string[] AllTags => _standartHtmlTags;
        public IDictionary<string, string[]> AttributeTags => _standartHtmlAttrubuteTagsDict;
        public string[] SelfClosingTags => _selfClosingTags;
		public string[] InputTypes { get { return _inputTypes; } }
    }
}
